version: '3.8'

services:
  petclinic:
    depends_on:
      - mysql
    image: nityansp/mavenjdkimage:1.1
    ports:
      - "8081:8080"
    environment:
      - PETCLINIC_DB=petclinic
      - PETCLINIC_DBUSER=petclinic
      - PETCLINIC_PASSWORD=petclinic

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    #  - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - ./conf.d:/etc/mysql/conf.d:ro
