version: '3.8'

services:
  petclinic:
    image: nityansp/petclinic:1.1
    ports:
      - "8081:8080"
    environment:
      - PETCLINIC_DB=petclinic
      - PETCLINIC_DBUSER=petclinic
      - PETCLINIC_PASSWORD=petclinic

