# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version 
#This vagrant file is specifically to provision for cogip application
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.network "private_network", ip: "192.168.33.11"
    config.vm.synced_folder ".", "/vagrant", :mount_options => ["ro"]
    config.vm.provision "docker" do |d| 
      d.run "nityansp/petclinic:1.3",
        args: "-p 8081:8080"
    end
end